services:
  accounts:
    image: "peteratef/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    networks:
      - eazybank

    deploy:
      resources:
        limits:
          memory: 700m
  cards:
    image: "peteratef/cards"
    container_name: cards-ms
    ports:
      - "8100:8100"
    networks:
      - eazybank
    deploy:
      resources:
        limits:
          memory: 700m
  loans:
    image: "peteratef/loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    networks:
      - eazybank
    deploy:
      resources:
        limits:
          memory: 700m
networks:
  eazybank:
    driver: "bridge"