server:
  port: 8090

spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  sql:
    init:
      mode: always
  profiles:
    active:
      - "qa"
  jpa:
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071"
management:
  endpoints:
    web:
      exposure:
        include: "*"